


ALUNO_FEDERALeUERJ16<-readRDS("C:/Users/Steven/Documents/GitHub/microdados_censo_superior_2016/ALUNO_FEDERALeUERJ16.rds")
ALUNO_FEDERALeUERJ16<-droplevels(ALUNO_FEDERALeUERJ16)


names(ALUNO_FEDERALeUERJ16)
head(ALUNO_FEDERALeUERJ16)

table(ALUNO_FEDERALeUERJ16$NO_IES,ALUNO_FEDERALeUERJ16$DS_NIVEL_ACADEMICO)  
table(ALUNO_FEDERALeUERJ16$NO_IES,ALUNO_FEDERALeUERJ16$DS_ALUNO_SITUACAO)
table(ALUNO_FEDERALeUERJ16$NO_IES,ALUNO_FEDERALeUERJ16$DS_MODALIDADE_ENSINO)

library(dplyr)
alunosmatriculadospresencial <-ALUNO_FEDERALeUERJ16 %>% 
  select(CO_IES, NO_IES, CO_CATEGORIA_ADMINISTRATIVA,DS_CATEGORIA_ADMINISTRATIVA,
 CO_ORGANIZACAO_ACADEMICA,   DS_ORGANIZACAO_ACADEMICA,  
 CO_CURSO,   NO_CURSO,  
 CO_CURSO_POLO,  CO_TURNO_ALUNO,
 DS_TURNO_ALUNO, CO_GRAU_ACADEMICO ,
 DS_GRAU_ACADEMICO, CO_MODALIDADE_ENSINO,
 DS_MODALIDADE_ENSINO,   CO_NIVEL_ACADEMICO,
 DS_NIVEL_ACADEMICO, CO_OCDE,
 NO_OCDE_AREA_GERAL, CO_OCDE_AREA_ESPECIFICA,   
 NO_OCDE_AREA_ESPECIFICA,CO_OCDE_AREA_DETALHADA,
 NO_OCDE_AREA_DETALHADA, CO_ALUNO_CURSO,
 CO_ALUNO_CURSO_ORIGEM,  CO_ALUNO,
 CO_COR_RACA_ALUNO,  DS_COR_RACA_ALUNO, 
 IN_SEXO_ALUNO,  DS_SEXO_ALUNO ,
 NU_ANO_ALUNO_NASC,  NU_MES_ALUNO_NASC, 
 NU_DIA_ALUNO_NASC,  NU_IDADE_ALUNO,
 CO_NACIONALIDADE_ALUNO, DS_NACIONALIDADE_ALUNO,
 CO_PAIS_ORIGEM_ALUNO,   CO_UF_NASCIMENTO  ,
 CO_MUNICIPIO_NASCIMENTO,IN_ALUNO_DEF_TGD_SUPER,
 CO_ALUNO_SITUACAO, DS_ALUNO_SITUACAO,  QT_CARGA_HORARIA_TOTAL,
 QT_CARGA_HORARIA_INTEG,DT_INGRESSO_CURSO,ANO_INGRESSO) %>%
  filter(DS_ALUNO_SITUACAO %in% c("Cursando", "Formado")) %>%
  #filter(DS_ALUNO_SITUACAO == "Cursando") %>%
  filter(DS_MODALIDADE_ENSINO=="Presencial")

# "Cursando" e "Formado"

table(alunosmatriculadospresencial$NO_IES,alunosmatriculadospresencial$DS_ALUNO_SITUACAO)
table(ALUNO_FEDERALeUERJ16$NO_IES,ALUNO_FEDERALeUERJ16$DS_ALUNO_SITUACAO)

table(ALUNO_FEDERALeUERJ16$NO_IES,ALUNO_FEDERALeUERJ16$DS_MODALIDADE_ENSINO)
table(alunosmatriculadospresencial$NO_IES,alunosmatriculadospresencial$DS_MODALIDADE_ENSINO)


